### ISSUE TITLE
Use the event delegation approach for adding DOM event listeners for better performance and improved usability

### ISSUE THREAD

**Issue by patrick-steele-idem** [raptorjs/marko-widgets#10]
Currently, widget developers must write their own code to attach DOM event listeners using jQuery or some other library. For example:

```javascript
function Widget() {
    var self = this;

    $(this.el).click(function(event) {
        self.doSomething();
    });
}
```

There are three problems with this approach:

1. Attaching listeners to every DOM element is slower than using event delegation (see http://davidwalsh.name/event-delegate)
2. The value of `this` is in the DOM event handler is the DOM element when it would be much more convenient if it was the widget.
3. It is difficult to remove DOM event listeners unless a reference to the original handle function is kept in a separate variable

To overcome these problems I propose the following solution:

Each Marko widget type should declare its DOM event handlers should code similar to the following:

```javascript
function Widget() {
    // ...
}

Widget.prototype = {
    doSomething: function() {

    },

    // *** DOM event listeners: ***
    domEvents: {
        'click': function(event) {
            // click listener on the root element
            this.doSomething();
        },

        'click #button1': function(event) {
            // click listener on a nested widget element
        },

        'click .foo': function(event) {
            // Delegate event with a CSS selector. Equivalent to $(this.el).on('click', '.foo', handler)
        },

        'resize window': function(event) {

        }
    }
}
```

The property names for the `domListeners` object should match the following format:

```
<event_type>[ <selector>]
```

Examples:

- `click`
- `click #someEl` (e.g. `<div w-el-id="someEl">`
- `resize window`

The `marko-widgets` module would lazily add DOM event listeners to the root `document.body` element to capture events that bubble up. For every event that is captured on the root `document.body` element, look at the `event.target` to figure out the target widget of the event (if any) using the following approach:

> When a DOM event is receive on the root element we could look at the target element of the event and from the target element we could get the associated widget. We could then see if the widget has a method to handle the DOM event and invoke the method (with “this” being the widget instance) and the first argument being the DOM event.

## Implementation

```javascript
var targetWidget; // The target widget instance
var targetWidgetEl; // The ID of the nested widget element (if applicable)

if (event.target.__widget) { // Handle events on the root element
    targetWidget = event.target.__widget;
} else if (event.target.id) { // Handle events on nested widget elements
    var separatorIndex = event.target.id.indexOf('-');
    if (separatorIndex !== -1) {
       var widgetId = event.target.id.substring(0, separatorIndex);
       targetWidget = markoWidgets.getWidgetForEl(widgetId);
       targetWidgetEl = event.target.id.substring(separatorIndex+1);
    }
}

var handler = getEventHandler(eventType, targetWidget, targetWidgetEl);
if (handler) {
    handler.call(widget, event);
}
```

<hr>

Thoughts? Concerns?

**Comment by patrick-steele-idem** [comment]
You can also find related discussion on the Gitter chat room for marko-widgets: https://gitter.im/raptorjs/marko-widgets

**Comment by devth** [comment]
:+1: in general. Syntax-wise, I like how Backbone does this: http://backbonejs.org/#View-extend

1. Much shorter "events" key (not that important)
2. css-style selector syntax is intuitive and more flexible than proposed format

**Comment by patrick-steele-idem** [comment]
Thanks for the feedback, @devth . 

> Much shorter "events" key (not that important)

Good point. All widget instances are [EventEmitter](http://nodejs.org/api/events.html#events_class_events_eventemitter) instances that support custom events and to avoid confusion between "DOM events" and "custom events" we were leaning towards "domListeners" (or "domEvents"?)

> css-style selector syntax is intuitive and more flexible than proposed format

We definitely considered the Backbone syntax in earlier discussions, but in general, we want to avoid using CSS selectors for performance reasons and instead we want to assign unique IDs to widget elements. With that said, I suppose we could leave the door open using a format similar to the following:

```javascript
{
    '#button1:click': function(event) {
        // click listener on a nested widget element
    },
    '.my-button:click': function(event) {
        // click listener on a nested widget element
    }
}
```

With that said, supporting CSS selectors for delegate events would complicate the implementation so I am not sure we want to support that out-of-the-box or give the appearance that it might be supported. Worth discussing some more.

Thanks again!

**Comment by devth** [comment]
Understandable regarding not supporting full-blown css selectors, but I do think even using `#button1:click` is more intuitive as the `#` indicates ID: the docs just need to be clear that is not full css selector support.

I like `domEvents`.

**Comment by philidem** [comment]
:+1: for `domEvents` and using Backbone syntax. Great feedback! Supporting CSS selectors should also be relatively easy (even if it doesn't perform as well)

**Comment by patrick-steele-idem** [comment]
After giving it some more thought I agree. Updated proposal:

```javascript
function Widget() {
    // ...
}

Widget.prototype = {
    doSomething: function() {

    },

    // *** DOM event listeners: ***
    domEvents: {
        'click': function(event) {
            // click listener on the root element
            this.doSomething();
        },

        'click #button1': function(event) {
            // click listener on a nested widget element
        },

        'click .foo': function(event) {
            // Delegate event with a CSS selector. Equivalent to $(this.el).on('click', '.foo', handler)
        },

        'resize window': function(event) {

        }
    }
}
```

**Comment by philidem** [comment]
How do you want to handle `#someId` that might appear in the CSS selector? This is kind of an edge case but you cannot pass the selector as-is to JQuery because `#someId` gets prefixed with the widget element ID. I think you might need to optimize for most common case (e.g. `click #someId`) but also handle edge cases like `click #someId input.some-class`.

I do worry a little about the extra overhead of parsing the property names so I would recommend caching a parsed version of the `domEvents` object in the object itself. That way, when setting up listeners for a widget, you could see if you've already parsed the `domEvents` object and avoid a lot of the string manipulation and testing to understand the property names. This is based on the assumption, that events won't be added to `domEvents` after it is first encountered (which I think is fine). If a lot of widgets are being instantiated this caching might prove useful. Considering the case where Marko widgets is used to render something like search results, there could be a lot of widget construction and parsing of `domEvents` object.

**Comment by patrick-steele-idem** [comment]
Valid concerns, @philidem 

+1 on caching the parsed domEvents.

We are already using a RegExp to parse query selectors and I think (but have not confirmed) that the overhead is minimal:
https://github.com/raptorjs/marko-widgets/blob/master/lib/Widget.js#L26

We should treat the following format as a special case and handle it similar to how it is being handled now: `<event> #<target>`

**Comment by pedramphp** [comment]
Looks great to me.

Thumbs up.

**Comment by RameshRM** [comment]
Random question thou, can the widget handle the behaviour from a another JS file.. which can be used in the Widget ? The benefit is writing the JS behaviours could be completely independant of the Widget and jQuery / vanilla JS or any pattern could be used

**Comment by patrick-steele-idem** [comment]
I am not sure I fully understand, @RameshRM. Are you asking if a widget constructor can call out to third-party/external code to add behavior? If that is your question, then, yes, the marko-widgets module makes no restrictions on what your widget does. All marko-widgets does now is instantiate a new widget instance given the widget ID, the root DOM element and some arbitrary widget config data. As a widget developer you can do whatever you want inside a widget constructor (such as calling out to a jQuery plugin).

With this proposal, we are hoping to solve the problem of efficiently attaching DOM event listeners because that is something that marko-widgets can do more optimally and more easily than if it were done outside of marko-widgets. Ideally, all widgets would take advantage of this functionality (when it is available), but it is still optional value-add.

**Comment by patrick-steele-idem** [comment]
Change in plans. After starting the implementation for this proposal we realized there was a simpler solution (both in implementation and usability) that avoids various caveats associated with this proposal. 

The new plan is to go forward with the following proposal:
https://github.com/raptorjs/marko-widgets/issues/11

I think you all will agree that the new proposal is an improvement over this proposal, but if there are any concerns or thoughts please let me know.
