### ISSUE TITLE
Initialize marko widgets while using SPF

### ISSUE THREAD

**Issue by viviangledhill** [raptorjs/marko-widgets#15]
[SPF](https://youtube.github.io/spfjs/) requests a page that uses marko widgets. For some cases we can't render templates / widgets on the client so we get a rendered widget through SPF. 

In order to get the widgets ready we can call the optimizer and add the css and js into the SPF head and foot. But how do we initialize now the widgets?

A solution would be to render a template with the "init-widgets" taglib separately. I feel like there is a better solution out there. Any recommendations?

**Comment by patrick-steele-idem** [comment]
I think you are looking for the following:

```javascript
var template = require('marko').load(require.resolve('./template.marko'));

template.render(viewModel, function(err, html, out) {
    var initWidgetsCode = require('marko-widgets').getInitWidgetsCode(out);

    var json = JSON.stringify({
            html: html,
            js: initWidgetsCode
        });
});
```

Then, on the client you can do:

```javascript
var serverOutput = ...;
document.body.innerHTML = serverOutput.html;
eval(serverOutput.js); // Initialize widgets rendered on the server
```

Sorry for lack of documentation :/ Pull Requests welcome :)

**Comment by viviangledhill** [comment]
Thanks! 
Sure, I'll prepare a pull request
