### ISSUE TITLE
Proposal: Rename defineWidget() to defineComponent()?

### ISSUE THREAD

**Issue by patrick-steele-idem** [raptorjs/marko-widgets#34]

**Comment by tindli** [comment]
Really supporting this!!!

Would make it more clear since the define code includes the template and can/should therefore be used even for rendering only purposes --> even if nothing is bind :+1:

**Comment by patrick-steele-idem** [comment]
I'm in favor as well. :thumbsup:

**Comment by philidem** [comment]
`defineWidget` has been renamed to `defineComponent`. Thanks @tindli!
