### ISSUE TITLE
issue with specifying widget filename when marko has w-body

### ISSUE THREAD

**Issue by mikewoo200** [raptorjs/marko-widgets#44]
I found an issue with specifying a filename for w-bind when there is a w-body in the template.

1) git clone and npm install
2) load page above; page loads; check the dom and you'll see that channel__wrapper div 
3) Now, make these changes:

- change "require: ./index" to "require: ./channel"
- change w-bind to w-bind="./channel"

4) load page above; page loads but the content is missing. I see the following channel__wrapper, but there is no content inside:
```
<div class="channel panel" id="w0" data-w-body="0">
    <div class="channel__wrapper" id="w0-0" data-w-onclick="handleClick|w0">
    </div>
</div>
```
5) The widget (channel.js) is loaded and initialized - i.e., alert() runs in init(), but there is no markup created.

Am I missing some step?

We would like to specify names for each module/widget, because we prefer not to have many index.js (which will become hard to find/differentiate).

**Comment by patrick-steele-idem** [comment]
Solved offline. For the potential benefit of others, there were issues because the same tag was being declared twice (once explicitly and another time via directory scanning). Closing this issue.
