### ISSUE TITLE
assigning w-id via invoked renderer

### ISSUE THREAD

**Issue by yomed** [raptorjs/marko-widgets#46]
Per https://github.com/raptorjs/marko/issues/94

It would be very useful to be able to assign w-id(s) to renderers that are directly invoked, such as:
```
<for each="renderer in data.renderers">
    <invoke function="renderer(myInputObject, out)" w-id="widget[]" />
</for>
```

**Comment by patrick-steele-idem** [comment]
Fixed. New version published: `marko-widgets@4.2.0`
