### ISSUE TITLE
Assigning w-id from a non-widget

### ISSUE THREAD

**Issue by jackhorton** [raptorjs/marko-widgets#49]
Is there any way to assign a special w-id to a widget when it is being called from a non-widget, but a parent is a widget? It would look something like this:

container.marko (this is a widget)
```html
<div w-bind>
    <intermediate-template>
</div>
```

intermediate-template.marko (this is *not* a widget)
```html
<div>
    <widget-one w-id="widget-one">
    <widget-two w-id="widget-two">
    <widget-three w-id="widget-three">
    <widget-four w-id="maybe-this-has-a-really-special-id">
</div>
```

widget-*.marko (this is a widget)
```html
<div w-bind>
    ...
</div>
```

In this sort of setup, the containing widget would have to bubble up through rendering calls. So, if the outer container was given the id `w28`, then maybe the sub widgets would just be `w28-widget-one`, `w28-widget-two`, and so on. Currently, this seems to require `intermediate-template.marko` to be widgetized, however the only purpose that I can see in this is for ID generation (If this is not the case and this is possible already, please let me know!).

**Comment by jackhorton** [comment]
Another use case for this actually has intermediate-template in a loop, so it is actually called as `<intermediate-template w-id="items[]" />`, even though we never actually use `items[x]`, only `items[x]-subwidget-id`. That use case is a bit more complex but could be tied to the same underlying process. I don't have any opinion one way or another on giving the intermediate template a `w-id`, but I would just like to be able to save on shipping down widget code if nothing will use it.

**Comment by patrick-steele-idem** [comment]
Hi @jackhorton, it seems reasonable that you might want to break up a UI component into multiple templates (hopefully within the single directory for the UI component). It seems pretty doable to support this, I'm going to need to take a closer look to get a better idea of the scope of work. I know it will require some changes to the compile-time transform that we are using to process the Marko template files, but I don't think the work is too much. I'll send an update soon. Thanks for opening the Github issue.

**Comment by patrick-steele-idem** [comment]
New version published with enhancement: `marko-widgets@4.2.2`

**Comment by patrick-steele-idem** [comment]
Hi @jackhorton, please let me know if things work as expected with the latest code that now allows `w-id` to be used in an intermediate template for a UI component. I have added a test case that validates the new functionality. Thanks.

**Comment by jackhorton** [comment]
This works, though not entirely as expected. Given my second example, where the intermediate template is called in a loop, we may want to namespace it a bit. 

Given a container.marko as such...
```html
<div w-bind>
    <intermediate-template w-id="group[]" />
</div>
```
... with everything else the same as in my original post, every single `widget-*.marko` is added directly to the `group[]` array. Even if we give the sub-widgets a declared w-id, it gets overwritten. So, in this example, the ids on the page turn out as follows: `w0`, `w0-group[0]`, `w0-group[1]`, `w0-group[2]`, `w0-group[3]`, rather than what I was expecting, `w0`, `w0-group[0]-widget-one`, `w0-group[0]-widget-two`, `w0-group[0]-widget-three`, `w0-group[0]-maybe-this-has-a-really-special-id`. Perhaps the worst problem is that if `intermediate-template` is given a non-array w-id, it still overwrites them all, but then you just have a bunch of nodes with "w0-group" as each one's ID, which will cause issues. 

So, the way that it exists now, at least in the array implementation, isn't really a problem for us, because we can still call getWidgets("group") on the container and get every widget south of it, which is what we are using it for. I guess the concern is that it will silently overwrite assigned w-ids on sub-widgets, and in the process would break getWidget() functionality. I have not determined what would happen if there was another sub-sub-widget in one of the sub-widgets, but i would imagine it also just gets added to the array.
