### ISSUE TITLE
expose out object inside define* functions

### ISSUE THREAD

**Issue by yomed** [raptorjs/marko-widgets#56]
I would like to be able to access `out.global` in my component definition, but `out` is not available in that scope.

Can access it here:
```
exports = module.exports = function (data, out) {
    data.name = out.global.config.name
    template.render(data, out);
};
```

But not here:

```
module.exports = require('marko-widgets').defineComponent({
    template: require('./template.marko'),
    getTemplateData: function(state, input) {
        return {
            name: out.global.config.name // out is undefined
        };
    }
});
```

**Comment by patrick-steele-idem** [comment]
Hi @yomed, sorry for not fully documenting it, but `out` will be the third argument to `getTemplateData(state, input, out)`. Here is the relevant code for reference: https://github.com/raptorjs/marko-widgets/blob/77f289dd4b12f803e96e54537dc32b2b11585e96/lib/defineRenderer.js#L168

I'm going to update the docs now. Please let me know if you run into any other issues. Thanks.
